#!/bin/sh

kb="$(setxkbmap -query | grep -oP 'layout:\s*\K\w+')" || exit 1

case $BLOCK_BUTTON in
1) kb=$(dmenukb) ;;
3) notify-send "⌨  Keyboard/language module" "$(printf "%s" "\- Current layout: $(setxkbmap -query | grep -oP 'layout:\s*\K\w+')")
- Left click to change keyboard." ;;
6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

case "$kb" in
"gb") KBD="GB" ;;
"ir") KBD="IR" ;;
"us") KBD="EN" ;;
*) KBD="unknown" ;;
esac
echo " $KBD"
