#!/bin/sh

case $BLOCK_BUTTON in
1) networkmanager_dmenu -l 10;;
3) notify-send "🌐 Internet module" "\- Click to connect
󰤭: no wifi connection
󰤥: wifi connection with quality
󰈂: no ethernet
󰈁: ethernet working
󰤪: vpn is active
";;
        6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null; then
    quality=$(awk '/^\s*w/ { print int($3 * 100 / 70) }' /proc/net/wireless)
    if [ "$quality" -ge 75 ]; then
        wifiicon="󰤨"
    elif [ "$quality" -ge 50 ]; then
        wifiicon="󰤥"
    elif [ "$quality" -ge 25 ]; then
        wifiicon="󰤢"
    else
        wifiicon="󰤯"
    fi
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null; then
    grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="󰤭" || wifiicon="󰤮"
else
  wifiicon="󰤣"

fi
printf "%s%s%s" "$wifiicon" "$(sed "s/down/󰈂/;s/up/󰈁/" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/󰤪/" /sys/class/net/tun*/operstate 2>/dev/null)"
